"""Initial migration

Revision ID: 09a00b8a5bf3
Revises: cdc283322d67
Create Date: 2025-08-24 09:16:15.110019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09a00b8a5bf3'
down_revision: Union[str, None] = 'cdc283322d67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Don't drop PostGIS system tables - they are owned by postgres user
    # op.drop_table('topology')
    # op.drop_table('layer')
    # op.drop_table('spatial_ref_sys')
    
    # Drop indexes if they exist
    try:
        op.drop_index('idx_bgeigie_logs_computed_location_gist', table_name='bgeigie_logs', postgresql_using='gist')
    except Exception:
        pass
    try:
        op.drop_index('idx_device_stories_last_location_gist', table_name='device_stories', postgresql_using='gist')
    except Exception:
        pass
    try:
        op.drop_index('idx_measurements_location_gist', table_name='measurements', postgresql_using='gist')
    except Exception:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create indexes if they don't exist
    try:
        op.create_index('idx_measurements_location_gist', 'measurements', ['location'], unique=False, postgresql_using='gist')
    except Exception:
        pass
    try:
        op.create_index('idx_device_stories_last_location_gist', 'device_stories', ['last_location'], unique=False, postgresql_using='gist')
    except Exception:
        pass
    try:
        op.create_index('idx_bgeigie_logs_computed_location_gist', 'bgeigie_logs', ['computed_location'], unique=False, postgresql_using='gist')
    except Exception:
        pass
    
    # Don't recreate PostGIS system tables - they should already exist
    # op.create_table('spatial_ref_sys', ...)
    # op.create_table('layer', ...)
    # op.create_table('topology', ...)
    # ### end Alembic commands ###
