"""Initial migration

Revision ID: 4f22cda92c24
Revises: 9b00ebec3499
Create Date: 2025-08-24 09:34:50.359223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f22cda92c24'
down_revision: Union[str, None] = '9b00ebec3499'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Don't drop PostGIS system tables - they are owned by postgres user
    # op.drop_table('topology')
    # op.drop_table('spatial_ref_sys')
    # op.drop_table('layer')
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Don't recreate PostGIS system tables - they should already exist
    # op.create_table('layer', ...)
    # op.create_table('spatial_ref_sys', ...)
    # op.create_table('topology', ...)
    pass
    # ### end Alembic commands ###
