"""Initial migration

Revision ID: c1ab831981bd
Revises: accb5ae6ed28
Create Date: 2025-08-24 09:32:11.907657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1ab831981bd'
down_revision: Union[str, None] = 'accb5ae6ed28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Don't drop PostGIS system tables - they are owned by postgres user
    # op.drop_table('spatial_ref_sys')
    # op.drop_table('layer')
    # op.drop_table('topology')
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Don't recreate PostGIS system tables - they should already exist
    # op.create_table('topology', ...)
    # op.create_table('layer', ...)
    # op.create_table('spatial_ref_sys', ...)
    pass
    # ### end Alembic commands ###
