"""Initial migration

Revision ID: cdc283322d67
Revises: 
Create Date: 2025-08-24 09:05:02.661629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'cdc283322d67'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_urn', sa.String(length=255), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('custodian_name', sa.String(length=255), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('last_location', geoalchemy2.types.Geometry(geometry_type='POINT', from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('last_location_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_device_stories_last_location_gist', 'device_stories', ['last_location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_device_stories_device_urn'), 'device_stories', ['device_urn'], unique=True)
    op.create_index(op.f('ix_device_stories_id'), 'device_stories', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('authentication_token', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('confirmation_sent_at', sa.DateTime(), nullable=True),
    sa.Column('time_zone', sa.String(length=255), nullable=True),
    sa.Column('moderator', sa.Boolean(), nullable=True),
    sa.Column('measurements_count', sa.Integer(), nullable=True),
    sa.Column('reset_password_token', sa.String(length=255), nullable=True),
    sa.Column('reset_password_sent_at', sa.DateTime(), nullable=True),
    sa.Column('remember_created_at', sa.DateTime(), nullable=True),
    sa.Column('sign_in_count', sa.Integer(), nullable=True),
    sa.Column('current_sign_in_at', sa.DateTime(), nullable=True),
    sa.Column('last_sign_in_at', sa.DateTime(), nullable=True),
    sa.Column('current_sign_in_ip', sa.String(length=255), nullable=True),
    sa.Column('last_sign_in_ip', sa.String(length=255), nullable=True),
    sa.Column('confirmation_token', sa.String(length=255), nullable=True),
    sa.Column('unconfirmed_email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_authentication_token'), 'users', ['authentication_token'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('device_story_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('device_story_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('image_content_type', sa.String(length=100), nullable=True),
    sa.Column('image_file_size', sa.Integer(), nullable=True),
    sa.Column('is_spam', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_story_id'], ['device_stories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_story_comments_id'), 'device_story_comments', ['id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('sensor', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('measurements_count', sa.Integer(), nullable=True),
    sa.Column('last_heard_from', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_table('measurement_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('UNPROCESSED', 'PROCESSED', 'SUBMITTED', 'APPROVED', 'DONE', 'REJECTED', name='importstatus'), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('rejected', sa.Boolean(), nullable=True),
    sa.Column('rejected_by', sa.String(length=255), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('measurements_count', sa.Integer(), nullable=True),
    sa.Column('lines_count', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measurement_imports_id'), 'measurement_imports', ['id'], unique=False)
    op.create_table('bgeigie_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cities', sa.String(length=255), nullable=True),
    sa.Column('credits', sa.String(length=255), nullable=True),
    sa.Column('height', sa.String(length=255), nullable=True),
    sa.Column('orientation', sa.String(length=255), nullable=True),
    sa.Column('auto_apprv', sa.Boolean(), nullable=True),
    sa.Column('would_auto_approve', sa.Boolean(), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('subtype', sa.String(length=50), nullable=True),
    sa.Column('status_details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['measurement_imports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('measurement_import_id', sa.Integer(), nullable=True),
    sa.Column('devicetype_id', sa.Integer(), nullable=True),
    sa.Column('sensor_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('original_id', sa.Integer(), nullable=True),
    sa.Column('replaced_by', sa.Integer(), nullable=True),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.Column('md5sum', sa.String(length=32), nullable=True),
    sa.Column('surface', sa.String(length=255), nullable=True),
    sa.Column('radiation', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['measurement_import_id'], ['measurement_imports.id'], ),
    sa.ForeignKeyConstraint(['original_id'], ['measurements.id'], ),
    sa.ForeignKeyConstraint(['replaced_by'], ['measurements.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_measurements_location_gist', 'measurements', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_measurements_id'), 'measurements', ['id'], unique=False)
    op.create_index(op.f('ix_measurements_md5sum'), 'measurements', ['md5sum'], unique=True)
    op.create_table('bgeigie_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_tag', sa.String(length=255), nullable=True),
    sa.Column('device_serial_id', sa.String(length=255), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('cpm', sa.Float(), nullable=True),
    sa.Column('cpm2', sa.Float(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('computed_location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('gps_validity', sa.String(length=10), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('battery_voltage', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('bgeigie_import_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bgeigie_import_id'], ['bgeigie_imports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bgeigie_logs_computed_location_gist', 'bgeigie_logs', ['computed_location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_bgeigie_logs_id'), 'bgeigie_logs', ['id'], unique=False)
    # Don't drop PostGIS system tables
    # op.drop_table('spatial_ref_sys')
    # op.drop_table('layer')
    # op.drop_table('topology')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topology',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('topology_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('precision', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('hasz', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='topology_pkey'),
    sa.UniqueConstraint('name', name='topology_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('layer',
    sa.Column('topology_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('layer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('schema_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('table_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('feature_column', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('feature_type', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('level', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('child_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['topology_id'], ['topology.id'], name=op.f('layer_topology_id_fkey')),
    sa.PrimaryKeyConstraint('topology_id', 'layer_id', name=op.f('layer_pkey')),
    sa.UniqueConstraint('schema_name', 'table_name', 'feature_column', name=op.f('layer_schema_name_table_name_feature_column_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_index(op.f('ix_bgeigie_logs_id'), table_name='bgeigie_logs')
    op.drop_index('idx_bgeigie_logs_computed_location_gist', table_name='bgeigie_logs', postgresql_using='gist')
    op.drop_table('bgeigie_logs')
    op.drop_index(op.f('ix_measurements_md5sum'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_id'), table_name='measurements')
    op.drop_index('idx_measurements_location_gist', table_name='measurements', postgresql_using='gist')
    op.drop_table('measurements')
    op.drop_table('bgeigie_imports')
    op.drop_index(op.f('ix_measurement_imports_id'), table_name='measurement_imports')
    op.drop_table('measurement_imports')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_device_story_comments_id'), table_name='device_story_comments')
    op.drop_table('device_story_comments')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_authentication_token'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_device_stories_id'), table_name='device_stories')
    op.drop_index(op.f('ix_device_stories_device_urn'), table_name='device_stories')
    op.drop_index('idx_device_stories_last_location_gist', table_name='device_stories', postgresql_using='gist')
    op.drop_table('device_stories')
    # ### end Alembic commands ###
