"""Initial migration

Revision ID: dec6de7d8c00
Revises: 09a00b8a5bf3
Create Date: 2025-08-24 09:18:02.516713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dec6de7d8c00'
down_revision: Union[str, None] = '09a00b8a5bf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Don't drop PostGIS system tables - they are owned by postgres user
    # op.drop_table('topology')
    # op.drop_table('layer')
    # op.drop_table('spatial_ref_sys')
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Don't recreate PostGIS system tables - they should already exist
    # op.create_table('spatial_ref_sys', ...)
    # op.create_table('layer', ...)
    # op.create_table('topology', ...)
    pass
    # ### end Alembic commands ###
